//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 02:15:37 AM MSK 
//


package by.training.taskxml.entity.tariffs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * <p>Java class for DateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}dateType"/>
 *         &lt;element name="finish" type="{http://www.w3.org/2001/XMLSchema}dateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateType", propOrder = {
    "start",
    "finish"
})
public class DateType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateType")
    protected Date start;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateType")
    protected Date finish;

    public DateType() {
        start = new Date();
        finish = new Date();
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setStart(Date value) {
        this.start = value;
    }

    /**
     * Gets the value of the finish property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getFinish() {
        return finish;
    }

    /**
     * Sets the value of the finish property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setFinish(Date value) {
        this.finish = value;
    }

    @Override
    public String toString() {
        return "DateType{" +
                "start=" + new SimpleDateFormat("dd.MM.yyyy").format(start) +
                ", finish=" + new SimpleDateFormat("dd.MM.yyyy").format(finish) +
                '}';
    }
}
