    //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 02:15:37 AM MSK 
//


package by.training.taskxml.entity.tariffs;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Internet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Internet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.training.by/tariffs}TariffType">
 *       &lt;sequence>
 *         &lt;element name="internet_price" type="{http://www.training.by/tariffs}NonNegativedecimal"/>
 *         &lt;element name="free_mgb" type="{http://www.training.by/tariffs}NonNegativedecimal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Internet", propOrder = {
    "internetPrice",
    "freeMgb"
})
public class Internet
    extends TariffType
{

    @XmlElement(name = "internet_price", required = true)
    protected double internetPrice;
    @XmlElement(name = "free_mgb", required = true)
    protected double freeMgb;

    /**
     * Gets the value of the internetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link double }
     *     
     */
    public double getInternetPrice() {
        return internetPrice;
    }

    /**
     * Sets the value of the internetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link double }
     *     
     */
    public void setInternetPrice(double value) {
        this.internetPrice = value;
    }

    /**
     * Gets the value of the freeMgb property.
     * 
     * @return
     *     possible object is
     *     {@link double }
     *     
     */
    public double getFreeMgb() {
        return freeMgb;
    }

    /**
     * Sets the value of the freeMgb property.
     * 
     * @param value
     *     allowed object is
     *     {@link double }
     *     
     */
    public void setFreeMgb(double value) {
        this.freeMgb = value;
    }

    @Override
    public String toString() {
        return "Internet{" +
                "internetPrice=" + internetPrice +
                ", freeMgb=" + freeMgb +
                ", name='" + name + '\'' +
                ", operatorName='" + operatorName + '\'' +
                ", payroll=" + payroll +
                ", dateType=" + dateType +
                ", idnumber='" + idnumber + '\'' +
                "}\n";
    }
}
