//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 02:15:37 AM MSK 
//


package by.training.tariffs;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Only_calls complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Only_calls">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.training.by/tariffs}TariffType">
 *       &lt;sequence>
 *         &lt;element name="call_prices" type="{http://www.training.by/tariffs}Call_prices"/>
 *         &lt;element name="free_minute" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="parameters" type="{http://www.training.by/tariffs}Parameters"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tarrifing" type="{http://www.training.by/tariffs}Tarrifing" default="oneminute" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Only_calls", propOrder = {
    "callPrices",
    "freeMinute",
    "parameters"
})
public class OnlyCalls
    extends TariffType
{

    @XmlElement(name = "call_prices", required = true)
    protected CallPrices callPrices;
    @XmlElement(name = "free_minute", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger freeMinute;
    @XmlElement(required = true)
    protected Parameters parameters;
    @XmlAttribute(name = "tarrifing")
    protected String tarrifing;

    /**
     * Gets the value of the callPrices property.
     * 
     * @return
     *     possible object is
     *     {@link CallPrices }
     *     
     */
    public CallPrices getCallPrices() {
        return callPrices;
    }

    /**
     * Sets the value of the callPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallPrices }
     *     
     */
    public void setCallPrices(CallPrices value) {
        this.callPrices = value;
    }

    /**
     * Gets the value of the freeMinute property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeMinute() {
        return freeMinute;
    }

    /**
     * Sets the value of the freeMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeMinute(BigInteger value) {
        this.freeMinute = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the tarrifing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarrifing() {
        if (tarrifing == null) {
            return "oneminute";
        } else {
            return tarrifing;
        }
    }

    /**
     * Sets the value of the tarrifing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarrifing(String value) {
        this.tarrifing = value;
    }

}
