//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 02:15:37 AM MSK 
//


package by.training.taskxml.entity.tariffs;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favorite_number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="connection_fee" type="{http://www.training.by/tariffs}NonNegativedecimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {
    "favoriteNumber",
    "connectionFee"
})
public class Parameters {

    @XmlElement(name = "favorite_number", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int favoriteNumber;
    @XmlElement(name = "connection_fee", required = true)
    protected double connectionFee;

    /**
     * Gets the value of the favoriteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getFavoriteNumber() {
        return favoriteNumber;
    }

    /**
     * Sets the value of the favoriteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setFavoriteNumber(int value) {
        this.favoriteNumber = value;
    }

    /**
     * Gets the value of the connectionFee property.
     * 
     * @return
     *     possible object is
     *     {@link double }
     *     
     */
    public double getConnectionFee() {
        return connectionFee;
    }

    /**
     * Sets the value of the connectionFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link double }
     *     
     */
    public void setConnectionFee(double value) {
        this.connectionFee = value;
    }

    @Override
    public String toString() {
        return "Parameters{" +
                "favoriteNumber=" + favoriteNumber +
                ", connectionFee=" + connectionFee +
                '}';
    }
}
